name: Close Stale Issues

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  close_stale_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write

    steps:
      - name: Close stale issues
        uses: actions/stale@v5
        with:
          stale-issue-message: >
            This issue has been marked as stale because it has been inactive
            for more than 14 days. Please update this issue or it will be
            automatically closed.
          days-before-issue-stale: 14
          days-before-issue-close: 0
          stale-issue-label: stale

          # Disable PR processing
          days-before-pr-stale: -1
          days-before-pr-close: -1

          # Only process issues, not PRs
          only-issue-labels: "*"
